/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';
import { NavigationItem } from './NavigationItem';

const navigationItems = ['Home', 'Productos', 'Sobre', 'Contacto'];

export const Navigation: React.FC = () => {
  return (
    <header>
      <nav className="flex flex-wrap gap-10 justify-between items-center px-24 leading-none max-md:px-5">
        <div className="flex gap-1 items-center self-stretch my-auto text-2xl text-black min-w-[240px]">
          <div className="flex shrink-0 self-stretch my-auto w-12 h-12" />
          <img 
            loading="lazy" 
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7d548b3008b82d2b80900e7c1ad1df209a9495c418f351ea911346082033b08?placeholderIfAbsent=true&apiKey=be8d47492ba34f5496a6e8a6c25f8fff" 
            alt="BabyPlants Boutique Logo" 
            className="object-contain shrink-0 self-stretch my-auto w-9 aspect-square" 
          />
          <h1 className="self-stretch my-auto">
            BabyPlants Boutique
          </h1>
        </div>
        
        <div className="flex gap-8 items-center self-stretch my-auto text-base whitespace-nowrap min-w-[240px] text-neutral-600">
          <ul className="flex gap-8 items-center">
            {navigationItems.map((item) => (
              <NavigationItem key={item} text={item} />
            ))}
          </ul>
          <button 
            className="self-stretch px-5 my-auto font-semibold text-center bg-black min-h-[40px] rounded-[50px] text-zinc-300"
            type="button"
          >
            Login
          </button>
        </div>
      </nav>
    </header>
  );
};