/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';

type NavigationItemProps = {
  text: string;
};

export const NavigationItem: React.FC<NavigationItemProps> = ({ text }) => (
  <li className="self-stretch my-auto">
    {text}
  </li>
);